version: "3.8"

services:
  psql-db:
    image: arm64v8/postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=taskapp
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=taskapp
    ports:
      - '5432:5432'

  recipe:
    container_name: recipe_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/taskapp
      - SPRING_DATASOURCE_USERNAME=taskapp
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db