version: "3.8"

services:
  db:
    image: arm64v8/postgres
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=taskapp
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=taskapp
    ports:
      - '5432:5432'

  app:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskapp
      - SPRING_DATASOURCE_USERNAME=taskapp
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      - db